name: Build

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 Building the code."

  deploy:
    needs: [build]
    name: Deploy to VSCode Marketplace
    environment: 'deploy'
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 Deploying the code."
